// ============================================================================
// reports.ts — Report generation (Markdown, CSV, JSON).
// PDF is delivered through the browser-printable report view (/r/[token]/print).
// ============================================================================
import type { ScanResult, Severity } from "./types";

const SEV_ORDER: Severity[] = ["critical", "high", "medium", "low", "info"];

export function buildMarkdown(result: ScanResult): string {
  const { meta, host, risk, ai } = result;
  const openPorts = result.ports.filter((p) => p.state === "open");
  const lines: string[] = [];
  lines.push(`# Portinel Security Report`);
  lines.push("");
  lines.push(`**Target:** \`${meta.target}\``);
  lines.push(`**Type:** ${meta.targetType}`);
  lines.push(
    `**IP address(es):** ${meta.ipAddresses.join(", ") || "unresolved"}`,
  );
  if (host.geo)
    lines.push(
      `**Geolocation:** ${host.geo.city ? host.geo.city + ", " : ""}${host.geo.country} (${host.geo.isp})`,
    );
  if (host.asn?.org) lines.push(`**Hosting:** ${host.asn.org} (${host.asn.number || "n/a"})`);
  lines.push(`**Scan date:** ${new Date(meta.finishedAt).toUTCString()}`);
  lines.push(`**Scan types:** ${meta.scanTypes.join(", ")}`);
  lines.push(`**Duration:** ${(meta.durationMs / 1000).toFixed(1)}s`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(`## Risk Score: ${risk.score}/100 (Grade ${risk.grade} — ${risk.label})`);
  lines.push("");
  lines.push("### Executive Summary");
  lines.push(ai.executiveSummary);
  lines.push("");
  lines.push("### Attack Surface");
  lines.push(
    `Estimated surface: **${ai.attackSurface.level}** (score ${ai.attackSurface.score}).`,
  );
  for (const f of ai.attackSurface.factors) lines.push(`- ${f}`);
  lines.push("");
  if (risk.deductions.length) {
    lines.push("### Score Breakdown");
    lines.push("| Finding | Severity | Impact |");
    lines.push("| --- | --- | --- |");
    for (const d of risk.deductions)
      lines.push(`| ${d.reason} | ${d.severity.toUpperCase()} | -${d.points} |`);
    lines.push("");
  }
  if (risk.positives.length) {
    lines.push("### Positives");
    for (const p of risk.positives) lines.push(`- ${p}`);
    lines.push("");
  }
  lines.push("## Findings");
  const sorted = [...result.findings].sort(
    (a, b) => SEV_ORDER.indexOf(a.severity) - SEV_ORDER.indexOf(b.severity),
  );
  for (const f of sorted) {
    lines.push(
      `### [${f.severity.toUpperCase()}] ${f.title}`,
    );
    lines.push(`*Category: ${f.category}*`);
    lines.push("");
    lines.push(f.description);
    if (f.evidence) lines.push(`> Evidence: \`${f.evidence}\``);
    lines.push("");
    lines.push(`**Recommendation:** ${f.recommendation}`);
    lines.push("");
  }
  lines.push("## Open Ports");
  if (openPorts.length) {
    lines.push("| Port | Protocol | State | Service | Product | Version |");
    lines.push("| --- | --- | --- | --- | --- | --- |");
    for (const p of openPorts)
      lines.push(
        `| ${p.port} | ${p.protocol} | ${p.state} | ${p.service} | ${p.product || "—"} | ${p.version || "—"} |`,
      );
  } else lines.push("_No open ports detected._");
  lines.push("");
  if (result.ssl.length) {
    lines.push("## TLS / SSL");
    for (const s of result.ssl) {
      lines.push(
        `### ${s.subjectCN} — grade ${s.grade} (${s.tlsVersion}, ${s.cipherName})`,
      );
      lines.push(`- Issuer: ${s.issuerCN}${s.issuerOrg ? ` (${s.issuerOrg})` : ""}`);
      lines.push(`- Valid: ${s.validFrom} → ${s.validTo} (${s.daysUntilExpiry}d left)`);
      lines.push(`- Signature: ${s.signatureAlgorithm} · Key: ${s.keyBits || "?"} bit ${s.keyType}`);
      if (s.weakConfigs.length) lines.push(`- Weaknesses: ${s.weakConfigs.join("; ")}`);
      lines.push("");
    }
  }
  if (result.technologies.length) {
    lines.push("## Technology Stack");
    for (const t of result.technologies) lines.push(`- ${t}`);
    lines.push("");
  }
  if (result.vulnerabilities.length) {
    lines.push(`## Known Vulnerabilities (${result.vulnerabilities.length})`);
    const sorted = [...result.vulnerabilities].sort((a, b) => b.cvss - a.cvss);
    lines.push("| CVE | Product | CVSS | Severity | Exploit | Description |");
    lines.push("| --- | --- | --- | --- | --- | --- |");
    for (const v of sorted)
      lines.push(`| ${v.cve} | ${v.product}${v.version ? ` ${v.version}` : ""} | ${v.cvss} | ${v.severity.toUpperCase()} | ${v.exploit ? "YES" : "no"} | ${v.title} |`);
    lines.push("");
  }
  if (result.subdomains.length) {
    lines.push(`## Subdomains (${result.subdomains.length})`);
    for (const s of result.subdomains.slice(0, 50))
      lines.push(`- ${s.hostname} — ${s.ips.join(", ")}`);
    lines.push("");
  }
  lines.push("---");
  lines.push("");
  lines.push("_Generated by Portinel — automated cyber reconnaissance platform._");
  return lines.join("\n");
}

export function buildPortsCSV(result: ScanResult): string {
  const rows = [["port", "protocol", "state", "service", "product", "version", "banner"]];
  for (const p of result.ports)
    rows.push([
      String(p.port),
      p.protocol,
      p.state,
      p.service,
      p.product || "",
      p.version || "",
      (p.banner || "").replace(/[\r\n,]/g, " "),
    ]);
  return rows.map((r) => r.map(csvCell).join(",")).join("\n");
}

export function buildFindingsCSV(result: ScanResult): string {
  const rows = [["title", "severity", "category", "description", "recommendation", "evidence"]];
  for (const f of result.findings)
    rows.push([
      f.title,
      f.severity,
      f.category,
      f.description,
      f.recommendation,
      f.evidence || "",
    ]);
  return rows.map((r) => r.map(csvCell).join(",")).join("\n");
}

function csvCell(v: string): string {
  if (/[",\n]/.test(v)) return `"${v.replace(/"/g, '""')}"`;
  return v;
}

export function buildJSON(result: ScanResult): string {
  return JSON.stringify(result, null, 2);
}
